Remove snapshot_loaded flag
iotaledger-archive/iota.rs pull request #1179
Opened 2022-08-08 09:51 UTC by Thoralf-M

# Description of change

Remove snapshot_loaded flag

## Links to any relevant issues

Fixes #1089 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Tests and running stronghold example from Python

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2022-08-15 08:51 UTC, thibault-martinez reviewed
Can you add an entry in the changelog please ?

2022-08-16 07:39 UTC, thibault-martinez commented on CHANGELOG.md
> +- Removed `snapshot_loaded` field from StrongholdAdapter;
Put that in a new `### Removed` section please

2022-08-16 08:15 UTC, thibault-martinez commented
Conflicts

2022-08-16 10:10 UTC, samuel-rufi requested changes

2022-08-16 10:10 UTC, samuel-rufi commented on CHANGELOG.md
> +- Removed `snapshot_loaded` field from StrongholdAdapter;
```suggestion

### Removed
- Removed `snapshot_loaded` field from StrongholdAdapter;
```

2022-08-16 15:02 UTC, thibault-martinez approved these changes

2022-08-17 08:47 UTC, samuel-rufi approved these changes

2022-08-17 08:54 UTC, merged