Fix: Added user agent to http client
iotaledger-archive/iota.rs pull request #1367
Opened 2022-11-09 22:57 UTC by kwek20

# Description of change

Allows users to set their user agent for http requests.
Certain servers discard requests without user agent set. 

Based on https://github.com/iotaledger/iota.rs/pull/775/files

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2022-11-10 08:39 UTC, Thoralf-M commented on client/src/node_manager/builder.rs
> +    /// % of nodes that have to return the same response so it gets accepted
Wrong comment

2022-11-10 08:39 UTC, Thoralf-M commented on client/src/node_manager/builder.rs
> +}
```suggestion
}

```

2022-11-10 14:56 UTC, thibault-martinez requested changes
Clippy + fmt

2022-11-10 20:00 UTC, Thoralf-M requested changes
Please also add an entry in the changelog https://github.com/iotaledger/iota.rs/blob/develop/client/CHANGELOG.md

2022-11-10 20:01 UTC, Thoralf-M requested changes
Please also add an entry in the changelog https://github.com/iotaledger/iota.rs/blob/develop/client/CHANGELOG.md

2022-11-10 20:01 UTC, Thoralf-M requested changes
Please also add an entry in the changelog https://github.com/iotaledger/iota.rs/blob/develop/client/CHANGELOG.md

2022-11-11 15:39 UTC, Thoralf-M approved these changes

2022-11-15 08:49 UTC, thibault-martinez approved these changes

2022-11-15 08:50 UTC, merged