Update wasm-bindgen version
iotaledger-archive/iota.rs pull request #1549
Opened 2023-02-03 10:02 UTC by olivereanderson

# Description of change
This PR bumps up the `wasm-bindgen` dependency in the Client Wasm bindings to version `0.2.84` (latest) and removes a lint that no longer applies (see [this PR](https://github.com/iotaledger/identity.rs/pull/1111) for more context). 

## How the change has been tested
Builds locally

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2023-02-03 10:05 UTC, Thoralf-M approved these changes
Thanks!

2023-02-03 10:05 UTC, thibault-martinez approved these changes, later dismissed
Thanks!

2023-02-06 08:41 UTC, Thoralf-M requested changes
In examine-wasm-bindings.yml we have
```
      # Download a pre-compiled wasm-bindgen binary.
      - name: Install wasm-bindgen-cli
        uses: jetli/wasm-bindgen-action@24ba6f9fff570246106ac3f80f35185600c3f6c9
        with:
          version: '0.2.83'
```
That needs to be updated

2023-02-06 08:47 UTC, thibault-martinez approved these changes

2023-02-06 08:48 UTC, Thoralf-M approved these changes

2023-02-06 08:57 UTC, merged