infra: Bump version to 0.4.0
iotaledger-archive/iota.rs pull request #28
Opened 2019-10-09 10:37 UTC by wusyong

Bump version to 0.4.0 across all crates. And also update information in README to sync with other different language libraries.

2019-10-09 13:12 UTC, njaremko commented
Why 0.2 -> 0.4? 0.3 seems to be unused.

Also, saying this official and such, you're implying that people should use the library with actual Iota, but this library hasn't been audited and it's test suite isn't very large, so I think that's irresponsible.

2019-10-09 13:26 UTC, wusyong commented
Right, I do mention it's beta software. But since we are transiting to bee as dependencies, it's better to back with WIP title in this case.

2019-10-14 03:50 UTC, oopsmonk requested changes
@wusyong you published this change to create.io but it should be after this PR merged.

2019-10-14 03:50 UTC, oopsmonk commented on Cargo.toml
>  description = "A rust implementation of the IOTA API"
```suggestion
description = "A rust implementation of the IOTA Client API"
```

2019-10-14 03:50 UTC, oopsmonk commented on README.md
> +Please report any issues in our [issue tracker](https://github.com/iotaledger/iota-lib-rs/issues).
```suggestion
Please report any issues in our [issue tracker](https://github.com/iotaledger/iota.rs/issues).
```

2019-10-14 03:50 UTC, oopsmonk commented on README.md
> +This is the **official** Rust client library, which allows you to do the following:
not yet. 
```suggestion
This is a Rust client library, which allows you to do the following:
```

2019-10-14 03:50 UTC, oopsmonk commented on README.md
> +This is beta software, so there may be performance and stability issues.
```suggestion
This client library is still in the beta stage, so there may be performance and stability issues.
```

2019-10-14 03:50 UTC, oopsmonk commented on README.md
> +```js
```suggestion
```rust
```

2019-10-14 04:40 UTC, oopsmonk requested changes

2019-10-14 04:40 UTC, oopsmonk commented on README.md
> +This is client library is still in the beta stage, so there may be performance and stability issues. As IOTA Foundation currently working on `bee`, we also decided to re-implement common libraries fo
```suggestion
This client library is still in the beta stage, so there may be performance and stability issues. As IOTA Foundation currently working on `bee`, we also decided to re-implement common libraries for security. This library is going to be feature freeze untill fundamental crates are done.
```

2019-10-14 04:40 UTC, oopsmonk commented on README.md
> +If you want to get involved in the community, need help with getting setup, have any issues related with the library or just want to discuss IOTA, Distributed Registry Technology (DRT) and IoT with o
```suggestion
If you want to get involved in the community, need help with setting up, have any issues related to the library or just want to discuss IOTA, Distributed Ledger Technology (DLT) and IoT with other people, feel free to join our [Discord](https://discord.iota.org/).
```

2019-10-14 06:34 UTC, oopsmonk approved these changes

2019-10-14 06:37 UTC, merged