iota-client refactoring
iotaledger-archive/iota.rs pull request #40
Opened 2020-03-25 05:32 UTC by wusyong

2020-03-25 05:50 UTC, oopsmonk commented
Can you elaborate your goal and what will be changed in the description?

2020-04-28 08:22 UTC, oopsmonk requested changes
lgfm, please fix typo and add doc. Let's file some issues for error handlings and brining back fmt.

2020-04-28 08:22 UTC, oopsmonk commented on .github/workflows/ci.yml
> -      - name: Run cargo fmt
Disable fmt temporally, file an issue to bring it back.

2020-04-28 08:22 UTC, oopsmonk commented on iota-client/client.rs
> +    /// Reattachments are usefull in case original transactions are pending, and can be done securely as many times as needed.
```suggestion
    /// Reattachments are useful in case original transactions are pending and can be done securely as many times as needed.
```

2020-04-28 08:22 UTC, oopsmonk commented on iota-client/core/get_transactions_to_approve.rs
> +    /// Set MWM depth
```suggestion
    /// the depth for the random walk in the tip selection
```

2020-04-28 08:22 UTC, oopsmonk commented on iota-client/extended/get_inputs.rs
> +            // If next couple of addresses dont have any balance, we determine it fails to prevent from infinite searching.
```suggestion
            // If the next couple of addresses don't have any balance, we determine it fails to prevent from infinite searching.
```

2020-04-28 08:22 UTC, oopsmonk commented on iota-client/extended/get_new_address.rs
> +            _ => panic!("Invalid security level"),
should not be panic. the caller should able to keep running with a warning or something else.
please file an issue and fix in another PR.

2020-04-28 08:22 UTC, oopsmonk commented on iota-client/extended/prepare_transfers.rs
> +            _ => panic!("Invalid scurity level"),
should not panic. as mentioned above.

2020-04-28 08:22 UTC, oopsmonk commented on iota-client/extended/send_transfers.rs
> +    /// Set MWM depth
```suggestion
    /// The depth of the random walk for GTTA
```

2020-04-28 08:22 UTC, oopsmonk commented on iota-client/extended/send_trytes.rs
> +    /// Set MWM depth
```suggestion
    /// the depth of the random walk for GTTA
```

2020-04-28 08:22 UTC, oopsmonk commented on iota-client/response.rs
> +/// Address as recipient to recieve iota
```suggestion
/// A transfer could be an input or an output for building a bundle.
/// input/output transfer depends on value, a negative value for an output transfer, a positive value for an input transfer
```

2020-04-28 08:22 UTC, oopsmonk commented on iota-client/util.rs
> +pub(crate) fn tx_trytes(tx: &Transaction) -> String {
documentation, please.

2020-04-28 10:02 UTC, wusyong commented on .github/workflows/ci.yml
> -      - name: Run cargo fmt
#43 opened.

2020-04-28 10:02 UTC, wusyong commented on iota-client/extended/get_new_address.rs
> +            _ => panic!("Invalid security level"),
#42 opened!

2020-04-28 11:02 UTC, oopsmonk requested changes

2020-04-28 11:02 UTC, oopsmonk commented on iota-client/core/attach_to_tangle.rs
> +        dbg!(&res);
remove.

2020-04-28 11:02 UTC, oopsmonk commented on iota-client/response.rs
> +    pub packets_queue_size: u16,
fix #41 
```suggestion
    pub packets_queue_size: Option<u16>,
```

2020-04-28 11:03 UTC, wusyong commented on iota-client/core/attach_to_tangle.rs
> +        dbg!(&res);
oops

2020-04-28 11:22 UTC, oopsmonk approved these changes

2020-04-28 11:22 UTC, merged