Support milestone id endpoint changes
iotaledger-archive/iota.rs pull request #968
Opened 2022-05-02 14:51 UTC by samuel-rufi

2022-05-02 15:06 UTC, Thoralf-M commented on src/node_api/core/routes.rs
> +    // })
Guess this can be deleted now

2022-05-02 15:21 UTC, thibault-martinez requested changes
Doesn't compile

2022-05-02 18:51 UTC, Thoralf-M approved these changes

2022-05-03 09:28 UTC, thibault-martinez approved these changes

2022-05-03 09:29 UTC, merged